# Використовуємо Python 3.9 як базовий образ
FROM python:3.9-slim

# Встановлюємо робочу директорію
WORKDIR /app

# Копіюємо файл залежностей (requirements.txt)
COPY requirements.txt .

# Встановлюємо залежності
RUN pip install --no-cache-dir -r requirements.txt

# Копіюємо всі файли до контейнера
COPY . .

# Відкриваємо порт для веб-сервера
EXPOSE 3000

# Запуск веб-сервера з uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "3000"]
